apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-svc
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.app.name }}
  ports:
    - port: 80
      targetPort: {{ .Values.containerPort }}

